version: '3.3' 

volumes:
  db-volume: # for windows

services: 
  web: 
    build: 
      context: .
      dockerfile: Dockerfile 
    container_name: php73 
    depends_on: 
      - db 
    volumes: 
      - ./www:/var/www/
    ports: 
      - 80:80 
      - 443:443

  db: 
    container_name: mysql56
    image: mysql:5.6 
    command: --default-authentication-plugin=mysql_native_password 
    restart: always 
    environment: 
      MYSQL_DATABASE: development 
      MYSQL_USER: dev 
      MYSQL_PASSWORD: dev 
      MYSQL_ROOT_PASSWORD: root 
      TZ: Asia/Tokyo 
    volumes:
      - db-volume:/var/lib/mysql # for windows
    ports: 
      - 33060:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - "PMA_HOST=db"
      - "PMA_USER=root"
      - "PMA_PASSWORD=root"

  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    depends_on:
      - web

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./www:/var/www
    working_dir: /var/www
    depends_on:
      - web

  npm:
    image: node:13.7
    container_name: npm
    volumes:
      - ./www:/var/www
    working_dir: /var/www
    entrypoint: ['npm']

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ./www:/var/www
    depends_on:
      - db
    working_dir: /var/www
    entrypoint: ['php', '/var/www/artisan']
    