version: '3.3' 
services: 
  web: 
    build: 
      context: .
      dockerfile: Dockerfile 
    container_name: php73 
    depends_on: 
      - db 
    volumes: 
      - ./www:/var/www/
      # - ./php:/var/www/
    ports: 
      - 80:80 
  db: 
    container_name: mysql56
    image: mysql:5.6 
    command: --default-authentication-plugin=mysql_native_password 
    restart: always 
    environment: 
      MYSQL_DATABASE: development 
      MYSQL_USER: dev 
      MYSQL_PASSWORD: dev 
      MYSQL_ROOT_PASSWORD: root 
    ports: 
      - 33060:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - "PMA_HOST=db"
      - "PMA_USER=root"
      - "PMA_PASSWORD=root"